### PR TITLE
Fixes the issue when back button returned all products instead of jus…

### LINKED ISSUE #825: Back button doesn't gets user back to the filtered category, but to all products instead
We have a "_Global Search on Category Page_" setting set to Yes and we have a problem.

if you go to any subcategory: shoes/styles/juniors (https://goo.gl/CFSl0a) , select any filter, like "size = 5" - you will see the filtered by size products. That's correct. 

After that try to hit Back button at browser and you will be back to shoes/styles/juniors page, but instead of seeing the products from that subcategory you will see the whole catalog, eventhough URL is correct...

I would expect, that we will see products from shoes/style/juniors - and now all the products.

### PR DESCRIPTION
**Pull request by JanPetr**
…t those on category page. At the same time removes the extra Algolia query on category page.

Fixes #825 #831

### CODE REVIEW

File: js/algoliasearch/instantsearch.js [hunk 1]
```diff
@@ -59,6 +59,22 @@ document.addEventListener("DOMContentLoaded", function (event) {
 			}
 		};
 		
+		if (algoliaConfig.request.path.length > 0 && window.location.hash.indexOf('categories.level0') === -1) {
+			if (algoliaConfig.areCategoriesInFacets === false) {
```
Comment (Inwerpsel) [inline js/algoliasearch/instantsearch.js]: Would be more readable to check for true:
``` javascript
if (algoliaConfig.areCategoriesInFacets) {
    instantsearchOptions.searchParameters = {
        hierarchicalFacetsRefinements: {
            'categories.level0': [algoliaConfig.request.path]
        }
    }
} else {
    ...
}
```

Comment (JanPetr) [inline js/algoliasearch/instantsearch.js]: Makes sense @Inwerpsel,
thanks for the review. I changed it and will merge it when tests passes ...
