### PR TITLE
Fixes the bug when searchableAttributes setting is returned from API …

### LINKED ISSUE #700: An error occurred while saving this configuration: You cannot specify "attributesToIndex" and "searchableAttributes" at the same time. "attributesToIndex" is deprecated you should only use "searchableAttributes"
/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php needs to be updated to use searchableAttributes instead of attributesToIndex

Currently the module only uses attributesToIndex, but app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php:mergeSettings will fetch searchableAttributes from Algolia settings and try to merge them together. This results in the final API request object containing both attributesToIndex and searchableAttributes.

### PR DESCRIPTION
**Pull request by JanPetr**
…and then both searchableAttributes and attributesToIndex are set to index which results in error

Fixes #700

### CODE REVIEW

File: app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php [hunk 1]
```diff
@@ -84,6 +84,11 @@ public function mergeSettings($index_name, $settings)
         } catch (\Exception $e) {
         }
 
+        if (isset($onlineSettings['searchableAttributes']) && isset($settings['attributesToIndex'])) {
+            $settings['searchableAttributes'] = $settings['attributesToIndex'];
+            unset($settings['attributesToIndex']);
+        }
+
```
Comment (maxiloc) [inline app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php]: I would go even further than that and replace by searchAttributes even when not the both of them are set

Comment (JanPetr) [inline app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php]: Updated, can you check?

File: app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php [hunk 2]
```diff
@@ -84,6 +84,16 @@ public function mergeSettings($index_name, $settings)
...
+        if (isset($onlineSettings['attributesToIndex'])) {
+            $onlineSettings['searchableAttributes'] = $onlineSettings['attributesToIndex'];
+            unset($onlineSettings['attributesToIndex']);
+        }
+
         $removes = array('slaves');
```
Comment (maxiloc) [inline app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php]: Yes better, it would make sense to rename it when we set it as well (https://github.com/algolia/algoliasearch-magento/blob/037bc15692035dbbc9c4d4cb67705f4455238478/app/code/community/Algolia/Algoliasearch/Helper/Entity/Producthelper.php#L269), wdyt ?

Comment (JanPetr) [inline app/code/community/Algolia/Algoliasearch/Helper/Algoliahelper.php]: Yes, let's do it now. Next release we gonna have events there and it'll cause a BC break. 
Good catch, thanks.
